replicaCount: 2

image:
  repository: myregistry.azurecr.io/user-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

keyVaultCSI:
  enabled: true
  tenantId: "<your-tenant-id>"
  keyVaultName: "<your-kv-name>"
  secrets:
    - objectName: "db-connection"
      objectType: secret
      key: "DATABASE_URL"
    - objectName: "smtp-username"
      objectType: secret
      key: "SMTP_USERNAME"
    - objectName: "smtp-password"
      objectType: secret
      key: "SMTP_PASSWORD"
    - objectName: "smtp-host"
      objectType: secret
      key: "SMTP_HOST"
    - objectName: "smtp-port"
      objectType: secret
      key: "SMTP_PORT"
