apiVersion: v1
kind: Service
metadata:
name: {{ include "hrms-frontend.fullname" . }}
spec:
selector:
app.kubernetes.io/name: {{ include "hrms-frontend.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
ports:
- port: {{ .Values.service.port }}
targetPort: http
name: http
type: {{ .Values.service.type }}