{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: {{ include "user-service.fullname" . }}
spec:
podSelector:
matchLabels:
{{- include "user-service.selectorLabels" . | nindent 6 }}
policyTypes: [Ingress, Egress]
ingress:
{{- toYaml .Values.networkPolicy.ingress | nindent 2 }}
egress:
{{- toYaml .Values.networkPolicy.egress | nindent 2 }}
{{- end }}