{{- if .Values.keyVaultCSI.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
name: {{ include "user-service.fullname" . }}-spc
spec:
provider: azure
parameters:
usePodIdentity: "false"
useVMManagedIdentity: "true"
userAssignedIdentityID: "" # set if using UAMI
keyvaultName: {{ .Values.keyVaultCSI.keyVaultName | quote }}
cloudName: ""
objects: |
array:
{{- range .Values.keyVaultCSI.secrets }}
- |
objectName: {{ .objectName }}
objectType: {{ .objectType }}
{{- if .key }}
key: {{ .key }}
{{- end }}
{{- end }}
tenantId: {{ .Values.keyVaultCSI.tenantId | quote }}
secretObjects:
- secretName: {{ include "user-service.fullname" . }}-db
type: Opaque
data:
- objectName: {{ (index .Values.keyVaultCSI.secrets 0).objectName }}
key: {{ (index .Values.keyVaultCSI.secrets 0).key }}
{{- end }}